// frameworks/vue/src/components/Form/Form.vue
<script setup lang="ts" generic="TSchema extends FormSchema = FormSchema">
import {
  type FormSchema,
  INTERNAL,
  type SubmitEventHandler,
} from '@formisch/core/vue';
import { handleSubmit } from '@formisch/methods/vue';
import { computed } from 'vue';
import type { FormStore } from '../../types/index.ts';

/**
 * Form component props interface.
 */
export interface FormProps<TSchema extends FormSchema = FormSchema> {
  /**
   * The form store instance.
   */
  of: FormStore<TSchema>;
  /**
   * The submit handler called when the form is submitted and validation succeeds.
   */
  onSubmit: SubmitEventHandler<TSchema>;
}

const props = defineProps<FormProps<TSchema>>();

const handler = computed(() => handleSubmit(props.of, props.onSubmit));
</script>

<template>
  <form
    novalidate
    :ref="
      (element) => {
        if (element) {
          // eslint-disable-next-line vue/no-mutating-props
          of[INTERNAL].element = element as HTMLFormElement;
        }
      }
    "
    @submit="handler"
  >
    <slot></slot>
  </form>
</template>

// frameworks/svelte/src/components/Form/Form.svelte
<script lang="ts" generics="TSchema extends FormSchema = FormSchema">
  import {
    INTERNAL,
    type FormSchema,
    type SubmitEventHandler,
  } from '@formisch/core/svelte';
  import { handleSubmit } from '@formisch/methods/svelte';
  import type { FormStore } from '../../types/index.ts';
  import type { Snippet } from 'svelte';
  import type { HTMLFormAttributes } from 'svelte/elements';

  /**
   * Form component props type.
   */
  export type FormProps<TSchema extends FormSchema = FormSchema> = Omit<
    HTMLFormAttributes,
    'on:submit' | 'onsubmit' | 'novalidate'
  > & {
    /**
     * The form store instance.
     */
    of: FormStore<TSchema>;
    /**
     * The submit handler called when the form is submitted and validation succeeds.
     */
    onsubmit: SubmitEventHandler<TSchema>;
    /**
     * The child elements to render within the form.
     */
    children: Snippet;
  };

  let { of, onsubmit, children, ...other }: FormProps<TSchema> = $props();

  const handler = handleSubmit(of, onsubmit);
</script>

<form {...other} novalidate onsubmit={handler} bind:this={of[INTERNAL].element}>
  {@render children()}
</form>
